# Generated by Django 2.0 on 2018-01-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180107_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='people',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
