# Generated by Django 2.0 on 2017-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20171225_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='shortdescription',
            field=models.CharField(default='Professor', max_length=200),
            preserve_default=False,
        ),
    ]
