# Generated by Django 2.0 on 2017-12-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_professor_shortdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorimage',
            name='person',
        ),
        migrations.AddField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='professor_portraits/'),
        ),
        migrations.DeleteModel(
            name='ProfessorImage',
        ),
    ]
