# Generated by Django 2.0 on 2017-12-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20171226_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='psuwebsite/media/professor_portraits/noimage.png', upload_to='professor_portraits/'),
        ),
    ]
