# Generated by Django 2.0.6 on 2018-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20180626_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('Core Team', 'Core Team'), ('Notable Contributors', 'Notable Contributors'), ('Founders', 'Founders')], default='Contributors', max_length=25),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='noimage.png', height_field=110, upload_to='psuwebsite/static/psuwebsite/img/headprofiles', width_field=80),
        ),
    ]
