# Generated by Django 2.0.6 on 2018-06-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20180626_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='noimage.png', height_field=110, upload_to='team_portraits', width_field=80),
        ),
    ]
