# Generated by Django 2.0.6 on 2018-06-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_auto_20180626_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('Core Team', 'Core Team'), ('Noted Contributors', 'Noted Contributors'), ('Founders', 'Founders')], default='Noted Contributors', max_length=25),
        ),
    ]
