# Generated by Django 2.0 on 2018-01-07 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 7, 19, 38, 48, 292453)),
        ),
    ]
