# Generated by Django 2.0 on 2017-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='bibfile',
            field=models.FileField(upload_to='bib_files/'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='paperfile',
            field=models.FileField(upload_to='paper_files/'),
        ),
    ]
