# Generated by Django 2.0.6 on 2018-07-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='bibfile',
            field=models.FileField(blank=True, upload_to='bib_files/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paperfile',
            field=models.FileField(blank=True, upload_to='paper_files/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
