# Generated by Django 2.0.6 on 2018-07-16 21:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20180712_1912'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publication',
            managers=[
                ('qs', django.db.models.manager.Manager()),
            ],
        ),
    ]
