# Generated by Django 2.0.6 on 2018-07-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20180716_1719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publication',
            managers=[
            ],
        ),
    ]
