# Generated by Django 2.0.5 on 2018-10-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('webpageurl', models.CharField(max_length=200)),
                ('image', models.FileField(default='noimage.png', upload_to='team_portraits')),
                ('category', models.CharField(choices=[('Core Team', 'Core Team'), ('Noted Contributors', 'Noted Contributors'), ('Founders', 'Founders')], default='Noted Contributors', max_length=25)),
            ],
        ),
    ]
