# Generated by Django 2.0 on 2017-12-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='imageurl',
            new_name='webpageurl',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='url',
        ),
        migrations.AddField(
            model_name='professorimage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Professor'),
        ),
    ]
