# Generated by Django 2.0 on 2017-12-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20171226_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='professor_portraits/'),
        ),
    ]
