# Generated by Django 2.0 on 2017-12-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20171226_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='occupation',
            field=models.CharField(choices=[('Postdoc', 'Postdoc'), ('PhD Student', 'PhD Student'), ('Masters Student', 'Masters Student'), ('Undergraduate', 'Undergraduate'), ('Staff', 'Staff')], default='Postdoc', max_length=25),
        ),
        migrations.AlterField(
            model_name='currentteam',
            name='occupation',
            field=models.CharField(choices=[('Postdoc', 'Postdoc'), ('PhD Student', 'PhD Student'), ('Masters Student', 'Masters Student'), ('Undergraduate', 'Undergraduate'), ('Staff', 'Staff')], default='Postdoc', max_length=25),
        ),
    ]
