# Generated by Django 2.0 on 2017-12-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20171226_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='image',
        ),
    ]
