# Generated by Django 2.0 on 2017-12-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_remove_alumni_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='major',
            field=models.CharField(default='Computer Science', max_length=200),
        ),
    ]
