# Generated by Django 2.0.6 on 2018-06-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20180116_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('webpageurl', models.CharField(max_length=200)),
                ('image', models.ImageField(default='noimage.png', upload_to='people_portraits/')),
                ('category', models.CharField(choices=[('Core', 'Core Team'), ('Contributors', 'Notable Contributors'), ('Founders', 'Founders')], default='Contributors', max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='alumni',
        ),
        migrations.DeleteModel(
            name='CurrentTeam',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
