# Generated by Django 2.0.6 on 2018-06-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20180626_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='TeamMember',
        ),
    ]
