# Generated by Django 2.0.6 on 2018-06-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20180626_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='fullname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='team_portraits'),
        ),
    ]
